### ISSUE TITLE
Flag original dates for observed days 

### ISSUE THREAD

**Issue by jbroudou** [pinzolo/flagday#3]
When an observed day (i.e. holidays that are moved because they are on a weekend) is returned would it possible to flag what the original date was rather than relying on a string suffix? 

Also, in some locations when a holiday falls on a weekend, it is moved to a weekday as an observed day. In some of these locations only the observed day is considered a holiday whereas in others both the observed and original days are considered holidays. This is an important distinction in some jurisdictions. 

Is there any chance of supporting an additional flag against observed holidays that indicate the original day is or isn't a holiday?

**Comment by pinzolo** [comment]
@jbroudou 

Hi, thanks your issue.
And sorry for my slowly response.
I released [v1.1.0](https://github.com/pinzolo/flagday/releases/tag/v1.1.0).
Is this version satisfied with your issue?

**Comment by jbroudou** [comment]
Yes @pinzolo , this is great.

Thanks
